In [1]:
import pandas as pd

In [2]:
df  = pd.read_csv("../data/mplads_completed_works_2026-08-22.csv")

In [3]:
df.head(10)

,Work ID,Work Description,Category,MP Name,Constituency,State,House,Final Amount (₹),Completed Date,Has Images,Average Rating,IDA
0,134703,Upgradation of Road from Madhavaram Village to...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,499993.0,2025-01-31T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)
1,135593,Construction of CC Road from Amudala Village t...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,448722.0,2024-12-05T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)
2,135595,Construction of CC road from Amudala Village t...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,448970.0,2024-12-05T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)
3,135639,Construction of Under Ground Drainage at Thala...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,440871.0,2025-08-20T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)
4,135640,Construction of Under Ground Draiange at Thala...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,500000.0,2025-03-03T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)
5,135641,Construction of Under Ground Drainage at Thala...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,489209.0,2025-03-03T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)
6,135642,Construction of Under Ground Drainage at Penum...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,477866.0,2025-02-08T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)
7,135643,Construction of Under Ground Drainage at Penum...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,200000.0,2025-02-08T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)
8,135645,Construction of CC Road in Payanagaripalli HW ...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,397837.0,2024-10-25T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)
9,135646,Construction of CC Road at Hand Borewell to Sr...,Normal/Others,DAGGUMALLA PRASADA RAO,CHITTOOR,Andhra Pradesh,Lok Sabha,99809.0,2024-10-25T00:00:00.000Z,True,NaN,CHITTOOR(DISTRICT COLLECTOR CHITTOOR_IDA)

In [4]:
df.columns

Index(['Work ID', 'Work Description', 'Category', 'MP Name', 'Constituency',
       'State', 'House', 'Final Amount (₹)', 'Completed Date', 'Has Images',
       'Average Rating', 'IDA'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43173 entries, 0 to 43172
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Work ID           43173 non-null  int64
 1   Work Description  43088 non-null  object
 2   Category          43168 non-null  object
 3   MP Name           43173 non-null  object
 4   Constituency      43173 non-null  object
 5   State             43173 non-null  object
 6   House             43173 non-null  object
 7   Final Amount (₹)  43173 non-null  float64
 8   Completed Date    43173 non-null  object
 9   Has Images        43173 non-null  bool
 10  Average Rating    4 non-null      float64
 11  IDA               43173 non-null  object
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 3.7+ MB

In [6]:
df.describe()

             Work ID  Final Amount (₹)  Average Rating
count   43173.000000      4.317300e+04             4.0
mean   176111.147384      5.475696e+05             2.0
std     49892.650168      1.024150e+06             2.0
min      1211.000000      8.448000e+03             1.0
25%    150791.000000      1.765280e+05             1.0
50%    178174.000000      3.000000e+05             1.0
75%    209142.000000      6.000000e+05             2.0
max    292762.000000      4.647040e+07             5.0

In [ ]:
print(df['Average Rating'].iloc[0])
df['Average Rating'].isnull().count()

nan

43173

:

In [12]:
df.shape

(43173, 12)