In [1]:
import pandas as pd

In [2]:
df  = pd.read_csv("../data/mplads_expenditures_2026-08-22.csv")

In [29]:
df.head(20)

,MP Name,Constituency,State,House,Work Description,Vendor,IDA,Expenditure Amount (₹),Expenditure Date,Payment Status
0,ADITYA YADAV,BADAUN,Uttar Pradesh,Lok Sabha,Lighting of public spaces,Electromech Enterpries,BUDAUN(DISTRICT MAGISTRATE BUDAUN_IDA),733960.0,2026-08-17T00:00:00.000Z,Payment In-Progress
1,ADITYA YADAV,BADAUN,Uttar Pradesh,Lok Sabha,Lighting of public spaces,Electromech Enterpries,BUDAUN(DISTRICT MAGISTRATE BUDAUN_IDA),733960.0,2026-08-17T00:00:00.000Z,Payment In-Progress
2,SUKANTA KUMAR PANIGRAHI,KANDHAMAL,Odisha,Lok Sabha,"Construction of roads, link roads, pathways or...",MEMBER SECY OB AND OC WWB BBSR,BOUDH(District Collector Boudh_IDA),3000.0,2026-08-17T00:00:00.000Z,Payment In-Progress
3,ANANTA NAYAK,KEONJHAR,Odisha,Lok Sabha,Construction of community centers and communit...,MEMBER SECY OB AND OC WWB BBSR,Kendujhar(DISTRICT COLLECTOR KEONJHAR_IDA),3610.0,2026-08-20T00:00:00.000Z,Payment In-Progress
4,SUKANTA KUMAR PANIGRAHI,KANDHAMAL,Odisha,Lok Sabha,Street lights,MEMBER SECY OB AND OC WWB BBSR,Nayagada(DISTRICT COLLECTOR NAYAGARH_IDA),1700.0,2026-08-21T00:00:00.000Z,Payment In-Progress
5,Vijay Baghel,DURG,Chhattisgarh,Lok Sabha,"Construction of roads, link roads, pathways or...",SARPANCH GRAM PANCHYAT CHANGORI,DURG(DISTRICT COLLECTOR DURG_IDA),350000.0,2026-08-18T00:00:00.000Z,Payment In-Progress
6,SUNIL BOSE,CHAMARAJANAGAR,Karnataka,Lok Sabha,Construction of buildings for community cultur...,KRIDL BHUSIRI ACCOUNT WORKS,Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAG...,250000.0,2026-08-20T00:00:00.000Z,Payment In-Progress
7,Vijay Baghel,DURG,Chhattisgarh,Lok Sabha,"Construction of roads, link roads, pathways or...",SARPANCH GRAM PANCHAYAT BATHENA,DURG(DISTRICT COLLECTOR DURG_IDA),350000.0,2026-08-18T00:00:00.000Z,Payment In-Progress
8,Ajay Kumar Mandal,BHAGALPUR,Bihar,Lok Sabha,Construction of water tanks,ASSISTANT ENGINEER NATHNAGAR,BHAGALPUR(DISTRICT PLANNING OFFICER BHAGALPUR_...,680912.0,2026-08-11T00:00:00.000Z,Payment In-Progress
9,ZIA UR REHMAN,SAMBHAL,Uttar Pradesh,Lok Sabha,Lighting of public spaces,R G SUPLLIER,SAMBHAL(DISTRICT MAGISTRAE BHIMNAGAR SAMBHAL_IDA),36159.0,2026-08-20T00:00:00.000Z,Payment In-Progress
10,ZIA UR REHMAN,SAMBHAL,Uttar Pradesh,Lok Sabha,Lighting of public spaces,R G SUPLLIER,SAMBHAL(DISTRICT MAGISTRAE BHIMNAGAR SAMBHAL_IDA),36159.0,2026-08-20T00:00:00.000Z,Payment In-Progress
11,BABU SINGH KUSHWAHA,JAUNPUR,Uttar Pradesh,Lok Sabha,Street lights,Ajay Kumar Singh,JAUNPUR(DISTRICT MAGISTRATE JAUNPUR_IDA),19992.0,2026-07-21T00:00:00.000Z,Payment In-Progress
12,BABU SINGH KUSHWAHA,JAUNPUR,Uttar Pradesh,Lok Sabha,Street lights,Ajay Kumar Singh,JAUNPUR(DISTRICT MAGISTRATE JAUNPUR_IDA),19992.0,2026-07-21T00:00:00.000Z,Payment In-Progress
13,BABU SINGH KUSHWAHA,JAUNPUR,Uttar Pradesh,Lok Sabha,Street lights,Ajay Kumar Singh,JAUNPUR(DISTRICT MAGISTRATE JAUNPUR_IDA),19992.0,2026-07-21T00:00:00.000Z,Payment In-Progress
14,BABU SINGH KUSHWAHA,JAUNPUR,Uttar Pradesh,Lok Sabha,Street lights,Ajay Kumar Singh,JAUNPUR(DISTRICT MAGISTRATE JAUNPUR_IDA),19992.0,2026-07-22T00:00:00.000Z,Payment In-Progress
15,BABU SINGH KUSHWAHA,JAUNPUR,Uttar Pradesh,Lok Sabha,Street lights,Ajay Kumar Singh,JAUNPUR(DISTRICT MAGISTRATE JAUNPUR_IDA),19992.0,2026-07-22T00:00:00.000Z,Payment In-Progress
16,BABU SINGH KUSHWAHA,JAUNPUR,Uttar Pradesh,Lok Sabha,Street lights,Ajay Kumar Singh,JAUNPUR(DISTRICT MAGISTRATE JAUNPUR_IDA),19992.0,2026-07-22T00:00:00.000Z,Payment In-Progress
17,BABU SINGH KUSHWAHA,JAUNPUR,Uttar Pradesh,Lok Sabha,Street lights,Ajay Kumar Singh,JAUNPUR(DISTRICT MAGISTRATE JAUNPUR_IDA),19992.0,2026-07-22T00:00:00.000Z,Payment In-Progress
18,BABU SINGH KUSHWAHA,JAUNPUR,Uttar Pradesh,Lok Sabha,Street lights,Ajay Kumar Singh,JAUNPUR(DISTRICT MAGISTRATE JAUNPUR_IDA),19992.0,2026-07-22T00:00:00.000Z,Payment In-Progress
19,BABU SINGH KUSHWAHA,JAUNPUR,Uttar Pradesh,Lok Sabha,Street lights,Ajay Kumar Singh,JAUNPUR(DISTRICT MAGISTRATE JAUNPUR_IDA),19992.0,2026-07-22T00:00:00.000Z,Payment In-Progress

In [24]:
df.tail(2)

,MP Name,Constituency,State,House,Work Description,Vendor,IDA,Expenditure Amount (₹),Expenditure Date,Payment Status
106261,Shri Jairam Ramesh (2022-28),Sitting Rajya Sabha,Karnataka,Rajya Sabha,"Construction of roads, link roads, pathways or...",KRIDL BHUSIRI ACCOUNT WORKS,CHIKKAMAGALURU(DEPUTY COMMISSIONER CHIKMAGALUR),800000.0,2024-10-15T00:00:00.000Z,Payment Success
106262,Shri Jairam Ramesh (2022-28),Sitting Rajya Sabha,Karnataka,Rajya Sabha,"Construction of roads, link roads, pathways or...",KRIDL BHUSIRI ACCOUNT WORKS,CHIKKAMAGALURU(DEPUTY COMMISSIONER CHIKMAGALUR),600000.0,2026-01-31T00:00:00.000Z,Payment Success

In [8]:
df.columns

Index(['MP Name', 'Constituency', 'State', 'House', 'Work Description',
       'Vendor', 'IDA', 'Expenditure Amount (₹)', 'Expenditure Date',
       'Payment Status'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106263 entries, 0 to 106262
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   MP Name                 106263 non-null  object
 1   Constituency            106263 non-null  object
 2   State                   106263 non-null  object
 3   House                   106263 non-null  object
 4   Work Description        106263 non-null  object
 5   Vendor                  106263 non-null  object
 6   IDA                     106263 non-null  object
 7   Expenditure Amount (₹)  106263 non-null  float64
 8   Expenditure Date        106263 non-null  object
 9   Payment Status          106263 non-null  object
dtypes: float64(1), object(9)
memory usage: 8.1+ MB

In [10]:
df.describe()

       Expenditure Amount (₹)
count            1.062630e+05
mean             3.687770e+05
std              6.527099e+05
min              1.000000e-02
25%              7.000000e+04
50%              1.999990e+05
75%              4.579810e+05
max              3.256225e+07

In [22]:
len(df[df["Constituency"]== "JAUNPUR"])

650

In [23]:
len(df[
    (df["Constituency"] == "JAUNPUR") &
    (df["Work Description"] == "Street lights")
])

593

In [25]:
len(df[
    (df["Constituency"] == "JAUNPUR") &
    (df["Work Description"] == "Street lights") &
    (df["Payment Status"] == "Payment Success" )
])

448

In [26]:
print (448 * 19992)

8956416

### Paid Amount: Eighty Nine Lakh fifty six thousand four hundred sixteen

In [ ]:
print (593 * 19992)

11855256

### After Payment Processing: One Crore Eighteen Lakhs fifty five thousand two hundred fifty six

In [28]:
print (11855256 - 8956416)

2898840

### Due Amount: Twenty Eight Lakhs Ninty Eight thousand eight hundred forty